### PR TITLE
Update `build.gradle` for Gradle 8

### PR DESCRIPTION
**Pull request by alexreg**
This gets the program building again with Gradle 8 (and some of these changes may even be needed for Gradle 7).

If everything looks in order, I would be grateful for a merge and another tagged release.

### CODE REVIEW

**Comment by apeltzer** [comment]
I would also advise to using https://nf-co.re/eager these days instead of the old EAGERv1 pipeline.

**Comment by alexreg** [comment]
@apeltzer Yes, I'd certainly prefer to use that, but unfortunately a paper that's just come out uses the old pipeline for some reason, and I'm trying to reproduce their results.

**Comment by apeltzer** [comment]
Ok fair enough then. I might build you a JAR file and tag it so you can reuse it.

**Comment by alexreg** [comment]
@apeltzer I think I have a nice working version now, but thank you, that would still be helpful. I'm not sure which of these tools remain actively in use, but I can gladly add some of them to the Homebrew bioscience package repository.

**Pull request merged**
